#!/usr/bin/env python3
"""Rebuild the project table in README.md from docs/_data/projects.yaml.

The README table was maintained by hand and had already drifted twice: a whole
stale copy of an older table was left below the current one with its header row
missing, so GitHub rendered it as a wall of pipes, and 15 never got added at
all. projects.yaml already drives the site, so it drives this too.

Rewrites only what sits between the marker comments. Run it after editing
projects.yaml; scripts/check-readme.sh fails CI if the two disagree.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
YAML = ROOT / "docs" / "_data" / "projects.yaml"
SITE = "https://tedens.github.io/devops-portfolio"


def find_readme():
    """The file is tracked as Readme.md. Hardcoding README.md worked on macOS,
    whose filesystem is case-insensitive, and broke the Pages build on Linux
    the first time it ran. Match on any casing rather than guessing one."""
    for candidate in sorted(ROOT.iterdir()):
        if candidate.is_file() and candidate.name.lower() == "readme.md":
            return candidate
    sys.exit(f"{ROOT}: no readme.md in any casing")


README = find_readme()

BEGIN = "<!-- BEGIN PROJECTS: generated by scripts/sync-readme.py -->"
END = "<!-- END PROJECTS -->"

# Only the scalar keys this script needs. projects.yaml also carries inline
# sequences (stack: [a, b]) which are skipped rather than half-parsed.
WANTED = ("title", "path", "summary", "status", "demo")


def load():
    """Parse the flat list-of-maps in projects.yaml. Not a general YAML reader:
    it handles exactly the shape this one file uses, and shouts if that shape
    changes rather than silently returning a short list."""
    entries, current = [], None
    for lineno, raw in enumerate(YAML.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].rstrip() if raw.lstrip().startswith("#") else raw.rstrip()
        if not line.strip():
            continue
        start = re.match(r"^- (\w+):\s*(.*)$", line)
        if start:
            current = {}
            entries.append(current)
            key, value = start.group(1), start.group(2)
        else:
            field = re.match(r"^  (\w+):\s*(.*)$", line)
            if not field:
                continue  # nested block or continuation; nothing here needs it
            if current is None:
                sys.exit(f"{YAML}:{lineno}: field before the first list item")
            key, value = field.group(1), field.group(2)
        if key in WANTED:
            current[key] = value.strip().strip('"')
    if not entries:
        sys.exit(f"{YAML}: parsed zero projects")
    return entries


def number(path):
    """/09-karpenter-spot-nodes/ -> 9. Sorts the table the way the folders sort."""
    m = re.match(r"^/(\d+)-", path)
    return int(m.group(1)) if m else 999


def table(entries):
    rows = ["| # | Project | What it does | Docs |", "|---|---------|--------------|------|"]
    for e in sorted(entries, key=lambda x: number(x.get("path", ""))):
        path = e.get("path", "")
        docs = f"[Docs]({SITE}{path})"
        flag = "" if e.get("status") == "live" else f" _({e.get('status')})_"
        rows.append(f"| {number(path):02d} | {e['title']}{flag} | {e['summary']} | {docs} |")
    return "\n".join(rows)


def main():
    text = README.read_text()
    if BEGIN not in text or END not in text:
        sys.exit(f"{README}: marker comments are missing; add {BEGIN} / {END}")
    block = f"{BEGIN}\n\n{table(load())}\n\n{END}"
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, text, flags=re.S)
    if new == text:
        print(f"{README.name} already in sync")
        return 0
    if "--check" in sys.argv:
        sys.exit(f"{README.name} is out of date with projects.yaml; run scripts/sync-readme.py")
    README.write_text(new)
    print(f"{README.name} project table rebuilt from {YAML.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
