title: "Anthony Edens – DevOps Portfolio"
description: "DevOps projects in CI/CD, Kubernetes, IaC, and Monitoring by Anthony Edens"
baseurl: "" 
url: "https://tedens.github.io"

theme: null
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
